language: r

warnings_are_errors: false

os:
  - linux
  - osx

r:
  - release

branches:
  only:
  - master
    
sudo: false

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

before_deploy:
  # Get PKGVER
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  # CHECK version type by counting dots (flaky)
  - 'export RELEASE=$(grep -o \\. <<< $PKGVER | wc -w)'
  - "echo $RELEASE"
  # Build binary and remove the source archive
  - "R CMD INSTALL --build ggplotFL_$PKGVER.tar.gz"
  - "rm ggplotFL_$PKGVER.tar.gz"
  # Look for packages
  - "export RELEASE_PKG_FILE=$(ls ggplotFL*gz)"
  - "echo $RELEASE_PKG_FILE"

deploy:
  provider: releases
  api_key:
    secure: q5HM2VWfWuc5GVUDRXpgwG0JBYVzFKyxexfcfw8L3rH5NdXxQEYXL9vdc4A4mkdPlfYd4c1WozM1L9wZXjYHnW9batFnmdHvhJp6c2FbGA/8xEMHT94iGafuiaoXahUNi2YtUSTry+ruoAanUNKdiYrmdva//LL9ZlesC1rJclQ=
  file: $RELEASE_PKG_FILE
  skip_cleanup: true
  draft: true
  on:
    repo: flr/ggplotFL
    # condition: "$RELEASE=2"
    # condition: $RELEASE =~ ^[0-9]+\.[0-9]+\.[0-9]+
